#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS
Transparently convert a String or SecureString object into a SecureString object

.DESCRIPTION
Transparently convert a String or SecureString object into a SecureString object

.PARAMETER InputVar
Parameter to convert into SecureString

.PARAMETER InputVarName
Original name of the input parameter (only used in the exception message)

.OUTPUTS
[System.System.Security.SecureString]
#>
function ConvertObjectTo-SecureString {
    [CmdletBinding()]
    Param(
        [System.Object]$InputVar,
        [string]$InputVarName
    )

    switch ($InputVar.GetType().FullName) {
        'System.System.Security.SecureString' {
            return $InputVar 
        }
        'System.String' {
            return ConvertTo-SecureString -String $InputVar -AsPlainText -Force
        }
        default {
            throw "Invalid argument for parameter '$InputVarName'. Valid types are 'System.String' or 'System.System.Security.SecureString'"
        }
    }
}

<#
.SYNOPSIS
Convert a secure string to a standard string.

.DESCRIPTION
Convert a secure string to a standard string (with backward compatibility for PS 5).

.PARAMETER SecureString
Specifies the secure string to convert to a standard string.

.OUTPUTS
[System.String]
#>
function CompatibleConvertFrom-SecureString {
    [CmdletBinding()]
    Param(
        [System.Object]$SecureString
    )

    switch ($PSVersionTable.PSVersion.Major) {
        7 {
            return ConvertFrom-SecureString -SecureString $SecureString -AsPlainText
        }
        5 {
            return [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
            )
        }
    }
}
